hackmd:
  build: hackmd
  #environment:
  #  - POSTGRES_USER=hackmd
  #  - POSTGRES_PASSWORD=hackmdpass
  volumes:
    - ./data/uploads:/hackmd/public/uploads
    - ./data/db:/hackmd/db
  ports:
    - "9999:3000"
